name             'oc_id_application'
maintainer       'Ryan Cragun'
maintainer_email 'ryan@chef.io'
license          'Apache 2.0'
description      'Installs/Configures oc_id_application'
long_description 'Installs/Configures oc_id_application'
version          '0.1.0'
